### ISSUE TITLE
Token handling

### ISSUE THREAD

**Issue by sadortun** [roopakv/google-photos#1]
Hi @roopakv !

Do you still plan in integrating functionality to manage token(s) and refreshToken ? 

Currently what kind of workaround do you use to ensure the accesToken is not expired ?

Thanks,
Samuel

**Comment by roopakv** [comment]
Hey @sadortun thank you for the comment. I would love to integrate token functionality. TBH I haven't spent much time thinking about the best way to expose this to users of the package.

Did you have any ideas? 

Let me also go do some research tonight

**Comment by sadortun** [comment]
@roopakv Sorry i might not be very helpful on this  ! I am new to the fantastic world of VueJS, it's a bit too early to propose architectural solutions :)

**Comment by sadortun** [comment]
@roopakv  I think you should constructt your library on a Google Client library and let (if i am not mistaken, Google Client handle tokens and refreshes )

**Comment by sadortun** [comment]
@roopakv  Awesome !

**Comment by roopakv** [comment]
Added some documentation and how you can use the photos lib after getting the access token. Let me know if that helps.

**Comment by sadortun** [comment]
Awesome !
