### ISSUE TITLE
Oauth token Expiration.

### ISSUE THREAD

**Issue by mddanishyusuf** [roopakv/google-photos#11]
Hey Roopakv,

I have a question about oAuth token expiration? One time generation will work?

**Comment by roopakv** [comment]
The google photos does not handle oauth. The suggestion I make is to use the official google lib to manage oauth.

Their instructions about refresh tokens are here: https://developers.google.com/identity/protocols/OAuth2

Happy to talk about moving the oauth into this library, but at the moment this lib is simply a wrapper around the API and I thought it didnt make sense to have auth here. Please re-open if this doesnt answer your question
