### ISSUE TITLE
support for bulk uploads

### ISSUE THREAD

**Issue by mcpengelly** [roopakv/google-photos#12]
Does this support bulk uploads? it uses batch upload in the api but im not sure how i would go about uploading something like a directory of images.

**Comment by ManuCart** [comment]
@mcpengelly, you can take a look of my script. It use this repo

**Comment by mcpengelly** [comment]
You're a lifesaver. Thanks! @ManuCart

**Comment by roopakv** [comment]
@ManuCart could you link to the script here so that anyone who finds this issue later doesn't need to search again. :)

**Comment by ManuCart** [comment]
I put the link in my previous comment but it has disappeared
Here it is :
https://github.com/ManuCart/Google-Photos-Metadata-Fixer

**Comment by mcpengelly** [comment]
@ManuCart https://github.com/roopakv/google-photos/pull/13 I added a pull request that supports multiple file uploads in a way that google recommends. Your code was very helpful for me in figuring out how to add photos to an existing album. Thanks for that!
