### ISSUE TITLE
How to list the photos from an album?

### ISSUE THREAD

**Issue by bigvanstudio** [roopakv/google-photos#21]
First, thanks for developing this... but, I do not know how to list all the items in an Album. 
Can you explain how to do so?
Thanks in advance!

**Comment by bigvanstudio** [comment]
Solved!! Sorry!

**Comment by roopakv** [comment]
@bigvanstudio glad you figured it out. please let me know if the documentation can be made better, happy to do so. Or feel free to send a PR too
