### ISSUE TITLE
Migrate away from request

### ISSUE THREAD

**Issue by Richienb** [roopakv/google-photos#24]
The `request` package is deprecated, it is recommended to migrate away from it.

I recommend switching to `got` but `@root/request` is also a very easy alternative that should work as a drop-in alternative here.

// @roopakv

**Comment by roopakv** [comment]
@Richienb i was going to try isomorphic-unfetch. Any reason you recommend got?

I will get the package updated this weekend

**Comment by Richienb** [comment]
@roopakv My motivation for recommending `got` is that it's a really feature-rich and easy-to-use request library. However, to also target browsers while remaining lightweight, I would recommend using [`ky`](https://www.npmjs.com/package/ky) with it's [`ky-universal`](https://www.npmjs.com/package/ky-universal) Node.js compatibility layer which is essentially a simplified fetch wrapper with error handling and URL search parameter encoding built-in.

**Comment by roopakv** [comment]
https://www.npmtrends.com/isomorphic-fetch-vs-ky-vs-got-vs-axios-vs-ky-universal

Based on this you are right, `got` is VERY popular, but to remain small for browsers i think `isomorphic-unfetch` or `axios` seem smaller and more popular.

thoughts?

**Comment by Richienb** [comment]
@roopakv isomorphic-unfetch is a cross-platform implementation of the window.fetch API. ky, on the other hand wraps the fetch API in a more simplified interface. This is why I recommend using it. Popularity-wise, they're not [too far apart](https://www.npmtrends.com/ky-vs-isomorphic-unfetch) either.

**Comment by roopakv** [comment]
@Richienb hmm, i guess even with `ky` i will need to add `ky-universal` but I do like the don't support too.

I'll try get to this this weekend, unless you want to send a PR

**Comment by Richienb** [comment]
> I do like the don't support too.

@roopakv What do you mean?

**Comment by roopakv** [comment]
aahh autocorrect. *deno support

**Comment by Richienb** [comment]
@roopakv In the meantime, do we also want to be migrating the codebase to Typescript?

**Comment by roopakv** [comment]
Yeah that'sb another to do. Probably will do this after
