### ISSUE TITLE
how use google photos api push picture/vedio to google photos

### ISSUE THREAD

**Issue by Shaiken** [roopakv/google-photos#3]
how use google photos api push picture/vedio to google photos

i don't know initial parameter after how do i do 
![image](https://user-images.githubusercontent.com/30071132/58160428-0c5d2f80-7cb1-11e9-93d2-563c6708d926.png)

**Comment by roopakv** [comment]
hi @Shaiken thank you for your question, im not sure i follow. are you asking abour where you get client ID and client secrets? if that is the case you can read more
- here https://www.npmjs.com/package/googleapis#oauth2-client
- and here https://developers.google.com/identity/protocols/OpenIDConnect

please re-open if this is not the problem you have

**Comment by Shaiken** [comment]
Thanks for your reply @roopakv 
![image](https://user-images.githubusercontent.com/30071132/58220379-35c59c00-7d41-11e9-8bc1-d3fa8a2e8b32.png)

i don't know  what is code 
i got a json file:
{
    "web": {
        "client_id": "xxxx", <---your_client_id
        "project_id": "xxxxx",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://oauth2.googleapis.com/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_secret": "xxxxxx", <--- your_client_secret
        "javascript_origins": [
            "http://xxxx" <--- your_redirect_url
        ]
    }
