### ISSUE TITLE
TimeoutError: Request Timed Out when uploading 3.5MB file

### ISSUE THREAD

**Issue by skybldev** [roopakv/google-photos#38]
I am uploading a relatively large file (3.47MB compared to an average 70KB image) on a slow internet connection (2.29Mbps) and the request times out after ~10 seconds.

Here is the code I'm using to upload it: 
```
let response = await photos.mediaItems.upload(
  cfg.googlePhotosAlbumID, "test", ".tempfile", "test");
```

And here is the error (forgive me for not catching it properly):

```
(node:19469) UnhandledPromiseRejectionWarning: TimeoutError: Request timed out
    at Timeout.<anonymous> (/home/lux/code/js-shinobiwebhook/node_modules/ky/umd.js:181:12)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:19469) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19469) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

EDIT: I think it's also worth mentioning that uploading succeeds consistently with aforementioned smaller images, except of course when the token expires.

Is there any way to keep the connection alive, and prevent it from timing out?

**Comment by roopakv** [comment]
Interesting!

Let me take a look at this and try repro and look at what a fix might be.

Does it happen on all large images irrespective of connection or is it the combination of both size and connection?

**Comment by skybldev** [comment]
Thank you! 

> Does it happen on all large images irrespective of connection or is it the combination of both size and connection?

I have tried uploading a video that is 5.75MB and it still times out, this time just as long (exactly 10.013s).

It finally worked when I connected to my mobile hotspot (18.6Mbps down, 8.5Mbps up) and uploaded that same 5.75MB file.

"Maybe it's a problem with Ky?", I thought and Googled, and some people have created issues on the project about not being able to set Ky's timeout to a larger value. I wasn't able to either.

**Comment by skybldev** [comment]
If you need a reproduction of it, this is the code I used to perform the test with the 5.75MB file, very similarly to how I did the first one. It is supposed to upload a local file named ".tempfile", request the information for it afterwards, and use its base URL to generate a direct link to the image.

*This assumes that the `photos` object is a `Photos()` object properly initialized and authenticated with Google APIs using the `googleapis` NPM package.*

```
async function getHostedLocalMediaURL(photos) {
	console.log(`:: Uploading file to Google Photos...`);

	var uploadStartTime = new Date();

	let response = await photos.mediaItems.upload(
		"My Album ID", "test", ".tempfile", "test")
		.catch((err) => {
			console.log(`Errored in ${new Date() - uploadStartTime}ms`);
		})
		.then((res) => {
			console.log(res);
			return res;
		});

	let qResponse = await photos.mediaItems.get(
		response.newMediaItemResults[0].mediaItem.id);

	return `${qResponse.baseUrl}=w${qResponse.mediaMetadata.width}-h${qResponse.mediaMetadata.height}`;
} 
```

**Comment by roopakv** [comment]
@skybldev that is so helpful! I will continue looking at it tonight. i had some issues repro-ing so this is going to be great

**Comment by roopakv** [comment]
@skybldev i've been trying to repro and i just uploaded a 7MB image. i used your script verbatim and still no issues. is there anything else that might be different in our environments?

**Comment by skybldev** [comment]
Probably our internet speed, since it's the most likely limiting factor, where Ky times out probably since the file doesn't upload fast enough. You might be able to use a throttler to limit the internet speed to simulate mine.

**Comment by skybldev** [comment]
@roopakv Okay, I think there is a solution to this, it turns out you *can* actually set Ky's timeout to a higher value, by using `timeout: number` in the post method....

In `lib/transport.js` line 23:

```js
  upload(fileName, filePath) {
    return ky
      .post('v1/uploads', {
        headers: {
          'Content-Type': 'application/octet-stream',
          Authorization: `Bearer ${this.authToken}`,
          'X-Goog-Upload-File-Name': fileName,
          'X-Goog-Upload-Protocol': 'raw',
        },
				body: fs.readFileSync(filePath),
				timeout: 15000
      })
      .text();
  }
```

And it works! I feel so stupid for not finding this out much earlier... 😅 

I will submit a PR that allows the user to set this very soon! Sorry for how long this strung out... :/

**Comment by roopakv** [comment]
Oh interesting! Great find!

Looking forward to the PR. Could we make it an option we can set ok the transport when constructing photos instead of setting it globally?

**Comment by skybldev** [comment]
The PR's up, and I made the changes you requested. :)
