### ISSUE TITLE
Finished with status: 'timeout'

### ISSUE THREAD

**Issue by individual8** [roopakv/google-photos#46]
Hi there,
I try to get the content of an album via
```
const photos = new Photos(access_token);
return await photos.mediaItems.search('albumId');
```

I run the code in a cloud function and the function times out without result.
`Function execution took 60026 ms, finished with status: 'timeout'`

If I query the same 'albumId' in Google's API reference, I get a result.
https://developers.google.com/photos/library/reference/rest/v1/mediaItems/search

Any ideas what I'm doing wrong?

**Comment by ivenuss** [comment]
+1 same for me

**Comment by shuuuuun** [comment]
I had this problem too, but in my case the following fix solved it.
https://github.com/roopakv/google-photos/pull/56

**Comment by roopakv** [comment]
thank you @shuuuuun published.
