### ISSUE TITLE
wrong function name on readme

### ISSUE THREAD

**Issue by Albembo** [roopakv/google-photos#58]
Sorry that's my first issue opened, so I don't know how I have to write it, I want to notify to you that on Readme, the upload multiple function is a wrong one, it should be something like that:
```js
const response = await photos.mediaItems.uploadMultiple(albumId, files, directoryPath, requestDelay);
```
Thank you

**Comment by roopakv** [comment]
i'll take a look this week

if you want to open a PR go ahead and do so :)
