### ISSUE TITLE
How to push media to an album

### ISSUE THREAD

**Issue by ManuCart** [roopakv/google-photos#8]
Hi,

I didn't find the method to push a media to an album with id
Is it exist ?
Please Help ?

**Comment by roopakv** [comment]
Did you already manage to push the raw image to google servers as described [here](https://developers.google.com/photos/library/guides/upload-media)

**Comment by ManuCart** [comment]
I uploaded photos with the application.
because I didn't find how to push raw image in nodejs
I nned help with this topic too

**Comment by roopakv** [comment]
Please look at the link above: https://developers.google.com/photos/library/guides/upload-media

You cannot upload via the app and then use this library because you wont have the uplaod token.

Once you upload there use `photos.albums.batchAddMediaItems`
